//
//  TestAudioFixtures.swift
//  QQPlayerTests
//
//  音频测试 fixture（base64 内嵌，免资源打包）：ffmpeg 合成 0.3s 440Hz 静音，
//  无版权。生成方法：
//    ffmpeg -f lavfi -i "sine=frequency=440:duration=0.3" -c:a libmp3lame -q:a 9 -write_id3v2 0 smoke-empty.mp3
//    ffmpeg -f lavfi -i "sine=frequency=440:duration=0.3" -c:a flac smoke-empty.flac
//    ffmpeg -f lavfi -i "sine=frequency=440:duration=0.3" -c:a aac -f ipod smoke-empty.m4a
//  （mp3 的 -write_id3v2 0 实测不生效，产物带空 ID3v2.4——正好覆盖"已有 tag 覆盖写"场景）
//  更新方法：替换文件后 `base64 -i <file> | tr -d '\n'` 更新下方常量。

import Foundation

enum TestAudioFixtures {
    /// 1x1 PNG（封面写入测试用）
    static let png1x1 = Data(base64Encoded: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==")!

    /// 把内嵌 fixture 解码写到临时目录唯一子目录，返回文件 URL
    static func writeFixture(_ name: String, base64: String, ext: String) throws -> URL {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("TagWriterTests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let url = dir.appendingPathComponent("\(name).\(ext)")
        try Data(base64Encoded: base64)!.write(to: url)
        return url
    }

    // smoke-empty.mp3（2023 字节）
    static let mp3Empty = "SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjYyLjEyLjEwMgAAAAAAAAAAAAAA//tAwAAAAAAAAAAAAAAAAAAAAAAAWGluZwAAAA8A" +
        "AAANAAAHugBbW1tbW1tba2tra2tra2t5eXl5eXl5eYaGhoaGhoaUlJSUlJSUlKGhoaGhoaGhr6+vr6+vr7y8vLy8vLy8ysrKysrK" +
        "ysrX19fX19fX5eXl5eXl5eXy8vLy8vLy8v////////8AAAAATGF2YzYyLjI4AAAAAAAAAAAAAAAAJASSAAAAAAAAB7otHo1WAAAA" +
        "AAD/+6DEAAADYBNd9DAAKL+Irf8wcgAAAAETVo4AAAAAwNzQAAAAQnDx4/UAAANdDw8CQCCrqACABgDgAAAAAAACJEqvW1xwle5N" +
        "Q98vAXiy09/fBaA3wGjw2/HhKd6gaErKA5igAAAAAFKnS2pDhnh0spLUOVyufbYHl6AADgC8QNDkI6COZrCuv6pMQU1FNC4wqqqq" +
        "qqqqqqqqqqqqqqqqqqqq/AX88AAAAAAyJJ0OODwDKoaQoiES7tgeXoAAIBoATwOgguIhgvKiz0xBTUU0LjCqqqqqqqqqqqqqqqqq" +
        "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqvwF/PAAAAAAMSUch1orBjYMokJEJsygK6wAAJoEYIXAqEdArM1hXX9VTEFNRTQuMFVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/Ab98AAAAAAyJJ0HOCgm1QshJgqJd2gO60AAIC1gl4ExSXOhWP1IwbVMQU1F" +
        "NC4wVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX8BfvgAAAAACSORVBaQXAy4KkzKITZlAd1oAAe4vJlwlKeh1q9" +
        "AIyPFUxBTUU0LjBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/AXs4AAAAAAyJJ0HOCgPqnTrxie/lANTgAD/" +
        "+yDE1QDC3Btn3PAAIEmDrfg2MAwYjQAnQJhh4YIFyiDVTEFNRTQuMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVX8BvzgAAAAADEcjkVaKwM2EJpkmNZcgNToAAe4+YXCUZ8TzswWDwpMQU1FNC4wqqqqqqqq//sQxOoAwrQdc8YlJiBJg634NLAE" +
        "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqvwG/OAAAAAAMhxOhTAsA1UhKXj1T+QATGAAAoLcM6ADDDyYcHiAS0xBTUU0" +
        "LjCqqqqqqqr/+xDE6oDCsB1zxjEiYEqDrXiWMEyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqr8BuzgAAAAADEckoqkXg5c" +
        "MvZJjWbIDU6AADxI+TLgiGfCOdqDYjhVTEFNRTQuMFVVVVVVVf/7EMTqgMK4HXPGPSQgSwOtuGY8DFVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVX8BvzgAAAAADIcUwpgWBVUTkTx6p/ZAanQAARHuH9AbDDyYcHiAS1MQU1FNC4wVVVVVfoG//sQxOqAwrwd" +
        "ccYtImBJg624x6SM3uAAAAAALBEU5p5PcpdnWxsZ/OVAQCENtgBwBAAwIAAAAAAAPgn24pUGIc9/vf5Sm4kJ/H3paf4BoBXPygbn" +
        "OUB9/oJggkxBTUU0LjCqqqqqqqr/+xDE6YDCnB1zxjGCIEaDrXiWJEyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqCAVhVd2v4" +
        "AAAEIlWCxEKhUiFSESliIVEyJEiARK8CgoFBQUFNf4KChQUNTEFNRTQuMKqqqqqqqv/7EMTpgMKkHXPGMSJgRQOteMYYjKqqqqqq" +
        "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq" +
        "qqqq//sQxOmAwqQdc8YtgiBHg6z4Zhgcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq" +
        "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqr/+xDE6gDClB1zxi0iYEoDrTiWJByqqqqqqqqqqqqqqqqqqqqqqqqqqqqq" +
        "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqv/7EMTpgMKgHXPGLYIg" +
        "RwOteGYYHKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq" +
        "qqqqqqqqqqqqqqqqqqqq//sQxPoAAtAdc9TwACDEiC5/MtAQqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq" +
        "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqr/+xDE64PFYCtZ/JGAKAAANIAAAASqqqqqqqqqqqqq" +
        "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqg=="

    // smoke-empty.flac（11876 字节）
    static let flacEmpty = "ZkxhQwAAACISABIAAARDAATjCsRA8AAAM66e7j17M6ZaywB+hW6wxmAdBAAALg0AAABMYXZmNjIuMTIuMTAyAQAAABUAAABlbmNv" +
        "ZGVyPUxhdmY2Mi4xMi4xMDKBACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/+FkIADxOAAABAAH/Av0D+ATuBeAGzOaoIRXt8hO912QfRB/3" +
        "xDMADCSeQzJJJPDMzmQmhnNJmSTTMnznJPJ55DPJyeScknmTkyaQyTmTnMzMmeZMyZ8k3DJ8k5kzDMzkh5D5MhpMmfJJeZck/J85" +
        "mSeSc5SENJk4ZkmSTJMzTJJw5DlCcmUybMzzPkpOTyZM5PJJyTmTOSTnOTJmZzlJNJM8mSkzmTOSZDmSZSGZTJmSHyTOTMkknMkz" +
        "PM5Pn5J85M8znkySZJzMyTJOYTJkmSckpzJmnNyczmSfJJOkJk5kmYTOczmeTmSTOZDMnkmcmTksmcycnmfMkzkJ2QyTyTMyHknQ" +
        "nmZJPMkzmfksyczzmZyTyGTkmTJMzJDLJnPh5M85meZmTwzJOScySZ5kmkkk8JPJJmckkk2SZkzNOeZNknzJPTJJmZnMPOZJzJJP" +
        "DmfOTOSHcJPJnPJkpDkyZySeQlkhsJzJkzMknnJMnyTzmSZycyXDpDOTkkshnMzOQych8hM5DJOTDJyZJPOfOSeZJnJymTmSZTJk" +
        "JmSSeSZMychnMJyT8kmZyTOcnM8mTMpOcM8nJmGZmcmc4SkzMPzmZk3kyTznJOTkpk88yZmSckkmmSZyTLMnJQzD+Q/lmczM+SSW" +
        "SSkkzmGZkmTIZ5JLhzOZh/JmkmcycmZZh+ZKSZOTJk5zOTJpPJnJOZzOmTPJkk+ZzmTk5DJzPJmZySTJJnMz4fkPJmSWSZ85zMzP" +
        "J5k2ZJMkmSTJk8kmcwnychmhmZkmczM5PlMmkkk9CTJyTSTnmTJMOSmSZyF5J8mc0knyZmScpmcmSwknkMySSTwzM5kJoZzSZkk0" +
        "zJ85yTyeeQzycnknJJ5k5MmkMk5k5zMzJnmTMmfJNwyfJOZMwzM5IeQ+TIaTJnySXmXJPyfOZknknOUhDSZOGZJkkyTM0yScOQ5Q" +
        "nJlMmzM8z5KTk8mTOTySck5kzkk5zkyZmc5STSTPJkpM5kzkmQ5kmUhmUyZkh8kzkzJJJzJMzzOT5+SfOTPM55MkmSczMkyTmEyZ" +
        "JknJKcyZpzcnM5knySTpCZOZJmEznM5nk5kkzmQzJ5JnJk5LJnMnJ5nzJM5CdkMk8kzMh5J0J5mSTzJM5n5LMnM85mck8hk5JkyT" +
        "MyQyyZz4eTPOZnmZk8MyTknMkmeZJpJJPCTySZnJJJNkmZMzTnmTZJ8yT0ySZmZzDzmScySTw5nzkzkh3CTyZzyZKQ5MmcknkJZI" +
        "bCcyZMzJJ5yTJ8k85kmcnMlw6Qzk5JLIZzMzkMnIfITOQyTkwycmSTznzknmSZycpk5kmUyZCZkknkmTMnIZzCck/JJmckznJzPJ" +
        "kzKTnDPJyZhmZnJnOEpMzD85mZN5Mk85yTk5KZPPMmZknJJJpkmckyzJyUMw/kP5ZnMzPkklkkpJM5hmZJkyGeSS4czmYfyZpJnM" +
        "nJmWYfmSkmTkyZOczkyaTyZyTmczpkzyZJPmc5k5OQyczyZmckkySZzM+H5DyZklkmfOczMzyeZNmSTJJkkyZPJJnMJ8nIZoZmZJ" +
        "nMzOT5TJpJJPQkyck0k55kyTDkpkmcheSfJnNJJ8mZknKZnJksJJ5DMkkk8MzOZCaGc0mZJNMyfOck8nnkM8nJ5JySeZOTJpDJOZ" +
        "OczMyZ5kzJnyTcMmtKv/+FkIATtO/Yz+i/+LAIwBjAKLA4cEf+aobRUz8c+672xPU1/RxEAABkzDMzmHkPkyGkyZzJJeZZJPyfOZ" +
        "knknOUhDSZOGZJyTJMzTJJw5DlCcmUyeZnmcyUnJ5Mmc+STknMmcknOcmTMznMk0kzyZMmcyZyTIcyTKQzKZMyQ/JnJmSSTmSZJ5" +
        "nJ8/JPnJnmc8mTyTmZkmScwmTJMk5JTmTNObk5nMk+SSdITJzkzCZzmczycySZzIZk8kzkknJSTOZOTzPmSZyE7IZJ5JmZDyehPM" +
        "ySeZJkzPycyczzmZyTyZOTkyTMyQyyZz4eTPOYZ5mZPDMk5JzJJnmSaSSbhnkkzOSSSbJMyZmmTzJsk+ZJ6ZJMzM5h5zJPkknhzP" +
        "nJnJD8JPJnPJkpDkyGcknkNkmwnMmTMySeckyfJPOZJnJzJmHkM5OSSyGczM5DJyHyEzwyTkwycmSTznzknmSZycpJOZJlMmQnnJ" +
        "5JzMnIZzCck5ySZnJM5yczyZMyk5wzycmYZmZyZzhKTMw8zmZk/JknnOScnJTJ55kzMk5JJ0yTOSZZk5KGYfyH8szmZnySSyTSSZ" +
        "zDMyTJkM8klw5nMw/kzSTOZOTJLMPzJSTJyZMnOZyZNJ5M5JzOZ0yZ5MknMznMnJyGSzPJmZySckmczPh+Q8mZJZJnznMyTPJ5k2" +
        "ckySczJk8kmcwnychmhmZkmczM5PlMmkkk9CTJyTSTnnMzDkpkmcheSeSZzSSfJmZJymZyZLJJ5DMySTwzM5kJoZzkzJJpmT5zkk" +
        "5PDyGeTk8k5JPMnJk0hknMnOZmZMPMmZM+Sbhk+ScyZhmZzDyHyZDSZM5kkvMskn5PnMyTyTnKQhpMnDMk5JkmZpkk4chyhOTKZP" +
        "MzzOZKTk8mTOfJJyTmTOSTnOTJmZzmSaSZ5MmTOZM5JkOZJlIZlMmZIfkzkzJJJzJMk8zk+fknzkzzOeTJ5JzMyTJOYTJkmSckpz" +
        "JmnNyczmSfJJOkJk5yZhM5zOZ5OZJM5kMyeSZySTkpJnMnJ5nzJM5CdkMk8kzMh5PQnmZJPMkyZn5OZOZ5zM5J5MnJyZJmZIZZM5" +
        "8PJnnMM8zMnhmSck5kkzzJNJJNwzySZnJJJNkmZMzTJ5k2SfMk9MkmZmcw85knySTw5nzkzkh+EnkznkyUhyZDOSTyGyTYTmTJmZ" +
        "JPOSZPknnMkzk5kzDyGcnJJZDOZmchk5D5CZ4ZJyYZOTJJ5z5yTzJM5OUknMkymTITzk8k5mTkM5hOSc5JMzkmc5OZ5MmZSc4Z5O" +
        "TMMzM5M5wlJmYeZzMyfkyTznJOTkpk88yZmSckk6ZJnJMsyclDMP5D+WZzMz5JJZJpJM5hmZJkyGeSS4czmYfyZpJnMnJklmH5kp" +
        "Jk5MmTnM5Mmk8mck5nM6ZM8mSTmZzmTk5DJZnkzM5JOSTOZnw/IeTMkskz5zmZJnk8ybOSZJOZkyeSTOYT5OQzQzMyTOZmcnymTS" +
        "SSehJk5JpJzzmZhyUyTOQvJPJM5pJPkzMk5TM5Mlkk8hmZJJ4ZmcyE0M5yZkk0zJ85yScnh5DPJyeScknmTkyaQyTmTnMzMmHmTM" +
        "mfJNwyfJOZMwzM5h5D5MhpMmcySXmWST8nzmZJ5JzlIQ0mThmSckyTM0yScOQ5QnJlMnmZ5nMlJycFxY//h5CAIPrT5O+yf8Hv0Z" +
        "/hb/FgAXARcCF+ao7hTz71e5T2kPXmAWQ92AGfJJyTmTOSTnOcmZnOUk0kzyZMmcyZyTIcyTKQzKZMyQ/OcmZJJOZJknmcnz8k+c" +
        "meYc8mTyTmZkmScwnMkyTklOZM05sk5nMk+SSdITJzJMwmc5nM8nMkmcyGZPJMySSclJM5k5PM+ZJnITshknkmZkPJ6E8zJJ5kmc" +
        "z8JzJzPOZnJPJk5OTJMzJDLJnPh5M85hnmZk8MyTknMkmeZJpJJuGeSTM5JJJskzJmaZMzJsk+ZJ6ZJMzM5h5zJPkknhzPnJnJD8" +
        "JPJnPJkpDkyGcknkNkmwnMmTMySeckyfJPOZJnJzJmHkM5OSSyGczM5DPIfITPDJOTDJyZJPOfOSeZJnJykk5kmUyZCecnknMych" +
        "nMJyTnJJmckznJzPJkzKTnDPJyZhmZnJnOEpMzDzOZmT8mSec5JyclMnnmTzJOSSdMkzkmWZOShmHnIfMszmZmckksnSSZzDMyTJ" +
        "kM8klw5nMw/kzSTOZOTJLMPzJSTJyZMnOZyZNJ5M5JzOZ0yZ5MknMznMnJyHLM8mZnJJySZzM+H5PJmSWSZ85zMkzyeZNnJMknMy" +
        "ZPJmcwnychmhmZkmczM5PlMmkkk9CTJyTSTnnMzDkpkmcheSeSZzSSfJmZJymZyZLJJ5DMySTwzM5kJoZzSZkk0zJ85yScnh5DPJ" +
        "yeScknmTkyaQyTmTnMzMmE5kzJnMk3DJ8k5kzDMzkh5D5MhpMmcySXmWST5JPOZknknOUhDSZOGZJyTJMzTJJw5DlCcmUybMzzOZ" +
        "KTJPJkznySck5kzkk5znJmZzlJNJM8mTJnMmckyHMkykMymTMkPznJmSSTmSZJ5nJ8/JPnJnmHPJk8k5mZJknMJzJMk5JTmTNObJ" +
        "OZzJPkknSEycyTMJnOZzPJzJJnMhmTyTMkknJSTOZOTzPmSZyE7IZJ5JmZDyehPMySeZJnM/CcyczzmZyTyZOTkyTMyQyyZz4eTP" +
        "OYZ5mZPDMk5JzJJnmSaSSbhnkkzOSSSbJMyZmmTMybJPmSemSTMzOYecyT5JJ4cz5yZyQ/CTyZzyZKQ5MhnJJ5DZJsJzJkzMknnJ" +
        "MnyTzmSZycyZh5DOTkkshnMzOQzyHyEzwyTkwycmSTznzknmSZycpJOZJlMmQnnJ5JzMnIZzCck5ySZnJM5yczyZMyk5wzycmYZm" +
        "ZyZzhKTMw8zmZk/JknnOScnJTJ55k8yTkknTJM5JlmTkoZh5yHzLM5mZnJJLJ0kmcwzMkyZDPJJcOZzMP5M0kzmTkySzD8yUkycm" +
        "TJzmcmTSeTOSczmdMmeTJJzM5zJychyzPJmZySckmczPh+TyZklkmfOczJM8nmTZyTJJzMmTyZnMJ8nIZoZmZJnMzOT5TJpJJPQk" +
        "yck0k55zMw5KZJnIXknkmc0knyZmScpmmfk="

    // smoke-empty.m4a（3773 字节）
    static let m4aEmpty = "AAAAHGZ0eXBNNEEgAAACAE00QSBpc29taXNvMgAAAAhmcmVlAAALZm1kYXTeAgBMYXZjNjIuMjguMTAyAAJgrFupUHImpXj14/eu" +
        "uJbVSWqWlSTJO4OhAQYVcvF3Gukta9peY8G7Y87q+TxS2DM+S+edNdI83c27i2DlLiOvtU21bNlU7VWfdVYjhWNxVxs2g2bG2LE3" +
        "Ky3LOdexOOxuKuNmuM9WY6Nfmr81fmsc+tn1tSz1LHRr81pmr81fn1s+tn1s+qn1+awzWGmzos6K1FailTYzMZmMzGitRWorUWNN" +
        "jMxmYxMaLOitRWosaLGZjMxiSiSniniiSiXwvkvklElPFPFPFEvkvkvkvvFPFPFPFEvkvxRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR" +
        "RcABNJra0k3AbMVMJsxUonTdTann61fDb41d1/6cfr9XBd6n/9Lz+vxwGrm//7fX7+0hq+M6El0EF/iaMDDx5cB9k07sFil8NqJh" +
        "dcGa0gu2J3ONIh8LF2uNghxsWpqprUEKl1U2cz/xtDXbv6zokGBruQSEgwMDZO4SEhIMDAzu4SEnAYcy7uEnGgZkGvO75BITkvz8" +
        "wNkZoTYS7/CFWGmriOkGSlFKpI3MrNnZVG5pa2222TRaRSmzmSqqi0zqYG+TA39ZCQYkDAwSEkrzgxs2EhJUGzcGBjYSElb2OaLG" +
        "UJK3YCCDLw4WY5eI+11/eH02VZV+U6JCTk00yVZyaYJS3eABFvYs9LYxF17vPf5z/GvrNcLYukkm5IeEiJIul0IDxjn3zn1n/TiP" +
        "MMRk0Pwjmu4HNX1WVfLM7LtP3vwPGbDCvWddW6txrKo5yxsuc7TibCpOGZNmzY0VEKxatWuDg2OOOMzA9eGGDiDTY44sgPXhhI7g" +
        "1OOMzID+/vCf4+G0+/uR/j4bT7+5P+PwZPv7yjN8G4AA6DYs0PouhgWhgOtVnj/+38/z/t/ji7m8lXouXvT+3jVLzW1aqZBPUgv6" +
        "QY2fo3QRzRlCheLzjm6eg87vf76Pf0PS5uirc61umXyTxHyXzCIKAckRnOCoSP8KmO2ktCSwGAocIlkVbNx2mrnwqYE2YUHFMGw6" +
        "VlY+eqs+XI3Y74sPUrg4n6EYXc2wgqGcGaUQOv9kp3A3LTsqb5Y4dNVjmBJfDDMhM5QwyCC7M5bf+62rYf0GJMi8AOY2LPFkDoWF" +
        "oWDo2FpH587//i9//z+PXnXGVrK87uys4qqx/3lWSlRQp25kKKAt5Q3N76dMBUI0PXKL4/+Qwb8qxwYZWlspd1CkmIaoYIcCOBYj" +
        "CJUsaI5NJm44MLnEiCZlJxcIpBdGoozv8PSaCiSJ+8kClReQeNlUDhAMLI1ickOBAsuhHhfAIQ5132qd2MLMcnDOFvwItJjoF4bY" +
        "sToQucF0bCwJUDdLA8KWj71Q8KVzFZ6qqTr760TnK0hE4BBprVAd6IGW3N14V+ii0pcb6IvmiM1N7EiV8LCloyFT2AqgV6RfwADq" +
        "NizwZkOFjobQoPQoPQvGu//7Xr/8/bXfxaZPPqq9siqlTKko/IqpWUJ5ppZWpBhxXFCb8tK6ZrQ9RUtbbNtiSrW2izosabOmtMxs" +
        "JpNFUOzzSM1gzidZhR9GExQDIBapipw2Xpe60MrKohEvdQWenpYESELDO6HO0K1YGZqBeihzNWlM5zQRyYCKvg7uE1SpQ8OuUSCZ" +
        "tn516nnY+D0H/x3LwJc6Atpd7nmWBbjvJ9MYMy+ESpEZfFr5YAlhr2xV7wIaJeP5Qbe42MBLzN3V3lP+XjCw+UsG1q3u6rmv04Qn" +
        "lfWPsVw6MsSruDKo/K9PwADcNiztNCaFCaFA6FA6V/F9//2vf/5+/mupLL5kxrcuqmQOUVFKgKe3iyZqCNnTrfk9fNR7oIqy7s77" +
        "Luy6y07r4WLLqRXK8QUXRkIJDAFGv+zqeQhZhaAQjCVYy4HBLCoZxUxQTKoEDyCbuqA9SvQ8A4I3JrEJnZfVya7UM9rJbZprhvv1" +
        "8H64xStvW4Q4IxkhziC3qU4LLsWQrEOspj6Tbn6FHCfX56NVPXEHTcHLa9kVOnrXqT9XseAA6DYs1GZMBYmhgOiYerfbz6//t/P/" +
        "z+/m/NbNIq0Kft5eFVKkooMxZhTJYtFR8LUZ9HxBd9geaMxzWOa5VibFYZJq2a44TSM+MkxM7VzV9cmIzWzams/ODLS6Wm4Je5vP" +
        "Okn/1NBMQcRpCYqkvuxKWQbxrvSbMAvtyle+1pyGIeTqgmEhOEeuacE2OwwNa7j78iZa75oa6kKKnrrloLBTrCmNTPZpcGC0Kz4A" +
        "5jYtbHpGigWucu//6W//b/bh7YZxjVquVT/qUSZeXvVTAPuBbWHW4GXJSDqSiRqvkJbrdExwx1rExxSHuD49PXVEu+SfOnOCharz" +
        "koArAFpSby5CGCMojJZU0IsIyklGrRfCWDSwZaUJbBrSQqmkalH11vnLVSaMPPJCBjDvl2vc3oNmqIBBNOQpKC8Op0MmyZ8Mg0k1" +
        "1vpuikCJFVuNEiwsFNU5/ADkNi1wqgsLQwHQwFhaJg6Jh6Zzzz//Y1/1/X4ntlO+K0m+JH9mXlUimbuhBxrxtTtPO1qQXIynYBM5" +
        "HHu8GFim2JTa7uMc/YjT3y7bJqqOUTBUtUWgpBOzASIgQxRUkABR7RoyShBlLaRjOUs4yhJnUEwstF1bEjJdKnnt6b/4BJJ7ikJb" +
        "SxDGEGkQwz+MopKy0s2k2xp69T4Wx4P3j39uDzCh7L2SUHI0AYdvJ4Spn+NSVn3iP0HIFokwHCWNfguEIMsQpVT2Gu2p5FMgmBwJ" +
        "HU4J+ADmNi1seEMfQsXSvfXj/+L9P/v/mV5KziFaqJWSVQ/pSopUEVpo68vltC6hT/q+2l/CjKfj7fDbeFd8NuaK3p41UPQ6DM8O" +
        "jpLDzrM84wpv17GEhIIjwDOY6KoWyIiSr+gTEiMGA6zQtwPAky6kRSAoYhQHCJvtNRRliAoTJjUtUSBNA1XwxlDxOYpHqdgJjxnL" +
        "ssunbEaZIRHBWlAxEPBxoRzO0wPwSZImrOjk6PACkplUZgzm4sw0OzE5iSWxDWjbPQN2gJ1M2MWidBIKhZZbHtVp77EIiBydkCCg" +
        "ZUBktGxNQG71a8GETkyt4ADgNizs5woVgo3QkJ/Fv/7Pj/+CV5vI42zi91IqZKlSphUgVUO4u3USFSQo/zeQ1zSlAbLsh793n926" +
        "mv3bte7HdrrprvrOtazkOs7cXUkrZ74QvU4AwHaDwiPeFLNH3fJzsVTKzbp/BijK+aIIao3T9zu6Exh8I9Jry+9vhV6q0x29IkRR" +
        "gsX46IH7EVpcG0ZOWUSayNXoAkv+2Z4ACDvnvIaW+T28xb6Cxdm7kSl5pJwHggsBSruPFdkIXoxEJwyE9s2EVZKMJaviNtutSiK2" +
        "VUxcmtChIjKQLU1nbgY7KjJhjCHinzXdDFyNqUhbTMD8APg2LXBUURBcy9//h4/+3VTqsTOfNWySrolEq9yrqqsdU/y7I4v+kef6" +
        "y3Ws51FQFDJEu4OAdv6sr2MpBjfmjcesMN9r0ff9jLsKM6JPoS6TN+I2hClKR5D8o0Z5AMj5z4AYWBuxuo0l4/KRtmPRA6MjM6za" +
        "mAma94Rfun9HU4QdoPwh8PBZYDSuM5u95iiv0l49k1aKLq0zwv7uKNmiufpFv69Gbs51sQwEfnNjlKTTE6a3Ol2eOda9Fl6qXVy3" +
        "FZKC87KkNsXpcAEqNi3QtBbAgta5/pf+nGZ1dKvOMquMjDyiSJEIfQ7d6GtMH7y1mkXkJBLdLYRVXwPFJJycmnkxxMRJkDKwOadf" +
        "SiD0zxffP7r7bx9w/NGp9U5iw2jJ7pDnbnZePgdvzd1k2VOZ+Pg91ydJt6y2qbrDQjxZ1HAmQ+S0ihPvTqMqWxHJaRgTIfJShQLe" +
        "KRSTA+SJGAZBQUhh4JumQa8eS3TKKejc9Flna4AAAAMzbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAAASwAAQAAAQAAAAAA" +
        "AAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAl10" +
        "cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAASwAAAAAAAAAAAAAAAEBAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAA" +
        "AAAAAAAAAABAAAAAAAAAAAAAAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAEsAAAEAAABAAAAAAHVbWRpYQAAACBtZGhkAAAA" +
        "AAAAAAAAAAAAAACsRAAAN65VxAAAAAAALWhkbHIAAAAAAAAAAHNvdW4AAAAAAAAAAAAAAABTb3VuZEhhbmRsZXIAAAABgG1pbmYA" +
        "AAAQc21oZAAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAABRHN0YmwAAABqc3RzZAAAAAAAAAAB" +
        "AAAAWm1wNGEAAAAAAAAAAQAAAAAAAAAAAAEAEAAAAACsRAAAAAAANmVzZHMAAAAAA4CAgCUAAQAEgICAF0AVAAAAAAEZWQABGVkF" +
        "gICABRIIVuUABoCAgAECAAAAIHN0dHMAAAAAAAAAAgAAAA0AAAQAAAAAAQAAA64AAAAcc3RzYwAAAAAAAAABAAAAAQAAAA4AAAAB" +
        "AAAATHN0c3oAAAAAAAAAAAAAAA4AAAECAAABAgAAAJMAAAC4AAAA6AAAAPMAAAC7AAAAqwAAAKcAAADVAAAA7QAAAPIAAADKAAAA" +
        "qQAAABRzdGNvAAAAAAAAAAEAAAAsAAAAGnNncGQBAAAAcm9sbAAAAAIAAAAB//8AAAAcc2JncAAAAAByb2xsAAAAAQAAAA4AAAAB" +
        "AAAAYnVkdGEAAABabWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAbWRpcmFwcGwAAAAAAAAAAAAAAAAtaWxzdAAAACWpdG9vAAAAHWRh" +
        "dGEAAAABAAAAAExhdmY2Mi4xMi4xMDI="

}
